//! # Homelab MCP
//!
//! MCP adapter LLMs.

use homelab_core::{tools::proxmox, Config, HomelabClient};
use rmcp::model::{Content, ErrorCode, ErrorData as McpError};
use rmcp::{handler::server::tool::ToolRouter, model::CallToolResult, tool, tool_router};
use rmcp::{tool_handler, ServerHandler};
use rmcp::{transport::stdio, ServiceExt};
use tracing::info;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .init();

    // Boot boundary: load runtime configuration before constructing the adapter.
    let config_path = std::env::var("HOMELAB_CONFIG").unwrap_or_else(|_| "config.toml".to_string());
    let config = Config::load(config_path)?;

    // Core dependency: HomelabClient knows how to call configured HTTP endpoints.
    let client = HomelabClient::new(config);

    info!("Starting homelab-mcp server...");

    // Adapter instance: owns core dependencies and exposes them as MCP tools.
    let server = HomelabMcp::new(client);

    // Transport boundary: speak MCP JSON-RPC over stdin/stdout.
    let service = server.serve(stdio()).await?;

    // Keep serving until the MCP transport shuts down.
    service.waiting().await?;

    info!("Shutting down...");
    Ok(())
}

// MCP adapter state. This is the "controller" object for MCP calls.
// It owns the core client and the generated dispatch table for tool methods.
pub struct HomelabMcp {
    // Core dependency used by tool methods to reach Proxmox/OPNsense/etc.
    client: HomelabClient,

    // Generated by #[tool_router]; rmcp uses this to map tool names -> methods.
    tool_router: ToolRouter<Self>,
}

// ServerHandler tells rmcp this struct is an MCP server.
// #[tool_handler] wires MCP list_tools/call_tool to the router.
#[tool_handler(
    name = "homelab-rs",
    version = "0.1.0",
    instructions = "Homelab automation tools backed by configured HTTP endpoints."
)]
impl ServerHandler for HomelabMcp {}

#[tool_router]
impl HomelabMcp {
    pub fn new(client: HomelabClient) -> Self {
        Self {
            client,
            // Self::tool_router() is generated by the #[tool_router] macro.
            tool_router: Self::tool_router(),
        }
    }

    // MCP entrypoint: external clients call tool name "scan_nodes".
    #[tool(name = "scan_nodes", description = "Scans proxmox nodes")]
    async fn scan_nodes(&self) -> std::result::Result<CallToolResult, McpError> {
        // Adapter -> core: call the real domain/tool function.
        let nodes = proxmox::scan_nodes(&self.client).await.map_err(|e| {
            McpError::new(
                ErrorCode::INTERNAL_ERROR,
                format!("Failed to scan nodes: {}", e),
                None,
            )
        })?;

        // Core result -> MCP content: serialize the domain data for the protocol response.
        let json = serde_json::to_string_pretty(&nodes).map_err(|e| {
            McpError::new(
                ErrorCode::INTERNAL_ERROR,
                format!("Failed to serialize nodes: {}", e),
                None,
            )
        })?;

        // MCP response: return one text content block containing JSON.
        Ok(CallToolResult::success(vec![Content::text(format!(
            "```json\n{}\n```",
            json
        ))]))
    }

    #[tool(name = "scan_cluster", description = "Scans proxmox cluster")]
    async fn scan_cluster(&self) -> std::result::Result<CallToolResult, McpError> {
        // Adapter -> core: call the real domain/tool function.
        let nodes = proxmox::scan_cluster(&self.client).await.map_err(|e| {
            McpError::new(
                ErrorCode::INTERNAL_ERROR,
                format!("Failed to scan clusters: {}", e),
                None,
            )
        })?;

        // Core result -> MCP content: serialize the domain data for the protocol response.
        let json = serde_json::to_string_pretty(&nodes).map_err(|e| {
            McpError::new(
                ErrorCode::INTERNAL_ERROR,
                format!("Failed to serialize clusters: {}", e),
                None,
            )
        })?;

        // MCP response: return one text content block containing JSON.
        Ok(CallToolResult::success(vec![Content::text(format!(
            "```json\n{}\n```",
            json
        ))]))
    }
}
